project:
  type: website
  output-dir: docs

website:
  title: "Orlando Acevedo-Charry"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd

  page-footer: 
    background: light
    left: © 2025 Orlando Acevedo-Charry
    right: This website was based on [Samantha Shanny-Csik](https://ucsb-meds.github.io/creating-quarto-websites/) impressive tutorial

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    page-layout: full

editor: visual

