---
title: "About"
subtitle: "A bit more about me!"
---

## {{< fa chalkboard-teacher title="A teacher at a chalkboard" >}} My academic path

I am a Colombian biologist with experience in conservation and field ecology, specially on birds, but also interested in other taxa (mammals, amphibians, reptiles, insects, etc). My research interests are broad, ranging from outreach and participative conservation programs to biodiversity monitoring, community ecology, population ecology, taxonomy, and biogeography.

During my undergrad studies (BSc) at the Universidad Nacional de Colombia in Bogotá, I dedicated much time in the field learning and teaching about bird conservation (and birdwatching). I had the role of bird monitor for several courses, including Animal Taxonomy (2 semesters), Field Ecology, and Ornithology. I was also coordinator of the student group of Ornithology – GOUN, where I get experience in monitoring biodiversity and management of human resources in research. I also explored the Orinoquian plainlands in Colombia through its birds (see [A las aves de mi llano](https://www.researchgate.net/publication/298354368_A_las_aves_de_mi_llano_un_recuento_de_avifauna_desde_el_folclore_de_la_Orinoquia_colombiana)). To complete my BSc, I conducted an inventory of birds at the eastern slopes of the Andes - Orinoco foothills regions of Colombia, in the Arauca Department. As a product of this research, I improved the ornithological knowledge of this understudied part of Colombia, highlighting the biogeographical relationships of the avifauna (see [Ornitologia Colombiana](https://asociacioncolombianadeornitologia.org/wp-content/uploads/2018/10/16eA0301-33.pdf)), as well as identified human-wildlife conflicts (see [Spizaetus](https://assets.peregrinefund.org/docs/newsletters/spizaetus-19-english.pdf)). 
 
Before start with my MSc, I conducted a workshop for more than 35 people on birdwatching and bird conservation in the Sibundoy valley of Putumayo, located in the southern Andes of Colombia. I trained the participants in bird identification and basic ecology through a series of short field trips (see [Universitas Scientiarium](https://revistas.javeriana.edu.co/index.php/scientarium/article/view/6195)), and they continue to generate new information on the avifauna of southern Colombia (see [Bulletin of the British Ornithologists' Club](https://boc-online.org/bulletins/downloads/BBOC1351-Acevedo-Charry.pdf)). This rewarding experience in Putumayo changed my life, and it made me realize the value and satisfaction of including community participation in biodiversity monitoring for conservation. Simultaneously to my MSc studies, I conducted another workshop on birdwatching and bird conservation in the Leguízamo municipality, located in the Amazon lowlands of Putumayo (see [Rev Acad Colom Cien Exac Fisi Nat](https://raccefyn.co/index.php/raccefyn/article/view/avifauna-del-interfluvio-de-la-cuenca-media-caqueta-putumayo-jap)). Some of my local collaborators in Putumayo are contributing with the Colombian bird inventory (see [Caldasia](https://revistas.unal.edu.co/index.php/cal/article/view/73468/72044), [Bulletin of the British Ornithologists' Club](https://bioone.org/journals/bulletin-of-the-british-ornithologists-club/volume-140/issue-2/bboc.v140i2.2020.a2/First-record-of-Rufous-thighed-Kite-Harpagus-diodon-in-Colombia/10.25226/bboc.v140i2.2020.a2.full), or [Boletín SAO](https://www.researchgate.net/profile/Orlando-Acevedo-Charry/publication/357057329_La_importancia_de_obtener_evidencia_multimedia_el_caso_de_los_semilleros_piquigordos_de_Colombia_con_registros_de_Sporophila_atrirostris_y_un_llamado_a_buscar_Sporophila_maximiliani/links/61ba07e34b318a6970e30606/La-importancia-de-obtener-evidencia-multimedia-el-caso-de-los-semilleros-piquigordos-de-Colombia-con-registros-de-Sporophila-atrirostris-y-un-llamado-a-buscar-Sporophila-maximiliani.pdf)).

To my MSc, I conducted a systematic review about the changes in diversity of terrestrial vertebrates (amphibians, reptiles, birds, and mammals) during secondary forest succession after agricultural abandonment (see [Oikos](https://nsojournals.onlinelibrary.wiley.com/doi/10.1111/oik.06252)). In addition, I studied the changes in soundscape activity in a deforested area in the Amazon lowlands of Putumayo, southern Colombia (In prep). Then, I got married with a lovely Boricua ([Zuania Colón-Piñeiro](https://www.researchgate.net/profile/Zuania-Colon-Pineiro)), which is my principal advisor in R, ggplot, and cooking.

I served as tropical researcher for the ARBIMON project in Puerto Rico during 2016-2017. In December 2016, I went to Madagascar for a collaboration with the Lost Forest of Ivohibory project lead by Dr. Patricia Wright from Stony Brook University and Centre ValBio.
 
I served as curator of the environmental sound collection (Colección de Sonidos Ambientales) at the Humboldt Institute, in the lovely town of Villa de Leyva, Colombia (3-4 hours from Bogotá) between January 2018 and May 2021. I was also the president of the Colombian Ornithological Association (ACO) between 2018-2020 and a reviewer in several journals, as well as iNaturalist and eBird, two excellent Community Science initiatives (see [Biological Conservation](https://www.sciencedirect.com/science/article/pii/S0006320721001294)).
 
I joined the Interdisciplinary Ecology PhD degree program at the University of Florida - School of Natural Resources and Environment in fall 2021 (GoGators!). I was awarded the College of Agricultural and Life Science Dean's Award. I have appointment with the Department of Wildlife Ecology and Conservation through my advisor Dr. Miguel A. Acevedo ([Quantitative Ecology Lab (2.0)](https://maacevedo.github.io)), and with the Florida Museum of Natural History with my advisor Dr. Scott K. Robinson ([Ordway Lab of Ecosystem Conservation](https://www.floridamuseum.ufl.edu/people/scott-robinson/)).